version: '3'
services:
  
  alice:
    image: kryha/parity:beta
    command:
      --config /parity/config/alice.toml
      --unsafe-expose
    volumes:
      - ./parity/config:/parity/config
    ports:
      - 8180:8180
      - 8546:8546
      - 8545:8545
    networks: 
      eth-net:
          ipv4_address: '10.1.0.11'


  bob:
    image: kryha/parity:beta
    command: --config /parity/config/bob.toml
      --unsafe-expose
    volumes:
      - ./parity/config:/parity/config
    ports:
      - 8544:8545
    networks: 
      eth-net:
          ipv4_address: '10.1.0.12'


  charlie:
    image: kryha/parity:beta
    command: --config /parity/config/charlie.toml
      --unsafe-expose
    volumes:
      - ./parity/config:/parity/config
    ports:
      - 8543:8545
    networks: 
      eth-net:
          ipv4_address: '10.1.0.13'

  ss1:
    image: kryha/parity:secretstore
    command:
      --config /parity/config/secret/ss1.toml
      --ws-interface 0.0.0.0
      --unsafe-expose
    volumes:
      - ./parity/config:/parity/config
    ports:
      - 8010:8010
    networks: 
      eth-net:
          ipv4_address: '10.1.0.21'

  ss2:
    image: kryha/parity:secretstore
    command:
      --config /parity/config/secret/ss2.toml
      --ws-interface 0.0.0.0
      --unsafe-expose
    volumes:
      - ./parity/config:/parity/config
    networks: 
      eth-net:
          ipv4_address: '10.1.0.22'

  ss3:
    image: kryha/parity:secretstore
    command:
      --config /parity/config/secret/ss3.toml
      --ws-interface 0.0.0.0
      --unsafe-expose
    volumes:
      - ./parity/config:/parity/config
    networks: 
      eth-net:
          ipv4_address: '10.1.0.23'

      
  monitor:
    image: buythewhale/ethstats_monitor
    volumes:
      - ./monitor/app.json:/home/ethnetintel/eth-net-intelligence-api/app.json
    networks: 
      eth-net:
          ipv4_address: '10.1.0.100'

  dashboard:
    image: buythewhale/ethstats
    volumes:
      - ./dashboard/ws_secret.json:/eth-netstats/ws_secret.json
    ports:
      - 3001:3000
    networks: 
      eth-net:
          ipv4_address: '10.1.0.200'

networks:
  eth-net:
      ipam:
        driver: default
        config:
            - subnet: 10.1.0.0/24